version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /RecipeOptimizer
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/RecipeOptimizer/app/chroma_db
      - .:/RecipeOptimizer
    env_file:
      - .env
    environment:
      - PYTHONPATH=/RecipeOptimizer
      - DATABASE_URL=sqlite+aiosqlite:////RecipeOptimizer/app/recipes.db
      - CHROMA_DIR=/RecipeOptimizer/app/chroma_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/openapi.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    command: >
      uvicorn app.backend.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend:/app
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - app

networks:
  default:
    driver: bridge